### ISSUE TITLE
Design Colour Pallette

### ISSUE THREAD

**Issue by CharlieMallon** [CharlieMallon/hackathonHero#17]

**Comment by DeanDodds** [comment]
![Image](https://user-images.githubusercontent.com/92326699/202900065-c5dd1dae-690d-4506-ae1a-663051e9a21e.png)

**Comment by HPCarey** [comment]
https://www.color-hex.com/color/7fff00
![Image](https://user-images.githubusercontent.com/101112811/202905993-0400ba7f-f941-4038-948f-3fce36412e16.png)



![Image](https://user-images.githubusercontent.com/101112811/202905999-b1e6165e-e355-4c85-9a12-1de289e3a79f.png)

**Comment by DeanDodds** [comment]
choose dance floor color palette
