### ISSUE TITLE
create Carousel for songs

### ISSUE THREAD

**Issue by CharlieMallon** [CharlieMallon/hackathonHero#19]
create a carousel to hold the songs - like a dukebox

**Comment by HPCarey** [comment]
Carousel styles and functionality written without song and image data

**Comment by JusJae** [comment]
Carousel now has music player and song title images uploaded to work on each click of buttons, but mute functionality needs to be added and volume of song playing to be amended.

**Comment by DeanDodds** [comment]
mute functionality added
