### ISSUE TITLE
Find songs for Carousel

### ISSUE THREAD

**Issue by CharlieMallon** [CharlieMallon/hackathonHero#20]
We need song name / artist / BMP and a credit for the readme (including where the song was dowloaded from)

**Comment by CharlieMallon** [comment]
@DeanDodds found this for downloading from youtube - https://youtubeto.org/en/youtube-mp3.html and this for cropping audio files - https://audiomass.co/

**Comment by JusJae** [comment]
These are 6 songs found and downloaded from YouTube using Downie (app) and then converted to mp3 from mp4 using Permute (app).
All original media is copyrighted by their respective owners. 
No copyright infringement is intended.

From Dance Dance Revolution I Playlist on YouTube - https://youtu.be/IMynxWftz74

        "name" : "Boom Boom Dollar",
        "artist" : "King Kong & Jungle Girls",
        "link" : "/assets/songs/Boom-Boom-Dollar--King-Kong-D-Jungle-Girls.mp3",
        "image" : "/assets/images/Boom-Boom-Dollar.jpg",
        "level": "hard",
        "bpm" : 135, 
https://www.youtube.com/watch?v=aCrDZBpEajI&list=PL83CD0C6F32574EE9&index=28

        "name" : "Get Up & Dance",
        "artist" : "Freedom",
        "link" : "/assets/songs/Get-Up-and-Dance--Freedom.mp3",
        "image" : "/assets/images/Get-Up-and-Dance.jpg",
        "level": "easy",
        "bpm" : 107,
https://www.youtube.com/watch?v=O9f9ZEplQrU&list=PL83CD0C6F32574EE9&index=64

        "name" : "Hero",
        "artist" : "Papaya",
        "link" : "/assets/songs/Hero-Papaya.mp3",
        "image" : "/assets/images/Hero.jpg",
        "level": "hard",
        "bpm" : 140,    
https://www.youtube.com/watch?v=IEHPafO_Svs&list=PL83CD0C6F32574EE9&index=21

        "name" : "Kung Fu Fighting",
        "artist" : "Bus Stop",
        "link" : "/assets/songs/Kung-Fu-Fighting--Bus-Stop-feat-Carl-Douglas.mp3",
        "image" : "/assets/images/Kung-Fu-Fighting.jpg",
        "level": "medium",
        "bpm" : 116, 
https://www.youtube.com/watch?v=pXXq7rCIJMU&list=PL83CD0C6F32574EE9&index=6 

        "name" : "Love",
        "artist" : "Sonic Dream",
        "link" : "/assets/songs/Love-Sonic Dream.mp3",
        "image" : "/assets/images/Love.jpg",
        "level": "easy",
        "bpm" : 97,
https://www.youtube.com/watch?v=SR5ye691tRA&list=PL83CD0C6F32574EE9&index=17
        
        "name" : "Shake your Booty (DDR Version)",
        "artist" : "KC & The Sunshine Band",
        "link" : "/assets/songs/Shake-Your-Booty--KC--The-Sunshine-Band.mp3",
        "image" : "/assets/images/Shake-Your-Booty.jpg",
        "level": "medium",
        "bpm" : 112,
  https://www.youtube.com/watch?v=bRkHPeij0OI&list=PL83CD0C6F32574EE9&index=114
