### ISSUE TITLE
choose Fonts

### ISSUE THREAD

**Issue by CharlieMallon** [CharlieMallon/hackathonHero#21]

**Comment by CharlieMallon** [comment]
https://fonts.google.com/specimen/Bungee+Shade?query=bungee+sha

Idea from huddle

**Comment by DeanDodds** [comment]
https://fonts.google.com/?query=bungee+

**Comment by HPCarey** [comment]
We went with bungee spice for the h1 headings, we went with bungee shade for the other headings and roboto for the paragraphs.
