### ISSUE TITLE
Design Wireframes

### ISSUE THREAD

**Issue by CharlieMallon** [CharlieMallon/hackathonHero#5]
Drop an idea image of what you think the game should look like

**Comment by DeanDodds** [comment]
![Image](https://user-images.githubusercontent.com/92326699/202536632-44e76d66-609a-4c4f-90fe-403c855a5fda.png)

**Comment by petrugio** [comment]
![Image](https://user-images.githubusercontent.com/25202682/202576116-abcb0bef-894f-4f35-829f-a6e3505a75e0.png)

**Comment by petrugio** [comment]
This is the gameplay page. We can add a modal with the instructions and another modal with a score at the end of the round/game. I think maybe cut the song to 1 minute because 2.5-4min is too long.
Also, we can add our GitHub pages, either in the footer or in a separate about team page.

**Comment by JusJae** [comment]
I have done the mobile view and web/tablet view. Focus on mobile view was the game with the information such as song title, bpm etc available from the "i" button.
"?" Would give the user access to the instructions again or a help screen.
![image](https://user-images.githubusercontent.com/42322548/202772288-17f304b3-f068-4c2e-a4df-7ceacf7799bb.png)!

![image](https://user-images.githubusercontent.com/42322548/202772336-1a99ad01-c6e2-4e45-aedf-af829fbdf9e3.png)

**Comment by petrugio** [comment]
Updated wireframes 


![Image](https://user-images.githubusercontent.com/25202682/202900082-c810e305-7842-4cf3-a4ed-0d50d53a69ed.png)
![Image](https://user-images.githubusercontent.com/25202682/202900083-83e80b49-f3c0-4d68-b357-93bdbb12d545.png)
![Image](https://user-images.githubusercontent.com/25202682/202900084-84a5ea44-9805-4d66-83d5-34167f09c666.png)
