### ISSUE TITLE
game name

### ISSUE THREAD

**Issue by CharlieMallon** [CharlieMallon/hackathonHero#6]

**Comment by petrugio** [comment]
Potential game name:
Game Dance
MindOfgame
The Dance Gamer
DrRhythm
Captain Rhythm
BigRhythm

**Comment by petrugio** [comment]
Rhythmtime
Rhythm Master Challenge
Rhythmlife
Rhythmworld
Rhythm Heroes

**Comment by DeanDodds** [comment]
Team voted Rhythm Heroes
